name: jb-git-tutorial
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.7.7
  - scipy>=1.5.0
  - pandas>=1.0.5
  - bokeh>=2.1.1
  - sphinx>=3.1.2
  - pip
  - matplotlib
  - pip:
    - jupyter-book>=0.7.4
