name: Test that Jupyter Book builds
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Build book
        run: make book
