name: Build and Deploy Jupyter Book
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    if: github.repository == 'PSLmodels/Git-Tutorial'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Build book
        run: make book

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: book/_build/html
